---
title: "My Project"
author: "Varun"
date: "2024-10-10"
output: "github_document"
---

```{r}
library(psych)
library(haven)
library(dplyr)
library(ggplot2)
library(bruceR)
library(performance)
library(sjPlot)
library(ggstatsplot)
library(Rmisc)
library(tidyverse)

```

#dataset
```{r}
load("C:/Users/vtrip/OneDrive/Desktop/ICPSR_38964/DS0001/38964-0001-Data.rda")
```

```{r}
new_dataset <- da38964.0001 %>%
  select(RES1, RES2, RES3, RES4, RES5, RES5, RES6, SAT1, SAT2, SAT3, SAT4, SAT5, SEX, LAD_NOW, LAD_FUT)

summary(new_dataset$SEX)

```


```{r}



new_dataset$RES1 <- as.numeric(new_dataset$RES1)
  


#describe(new_dataset$RES1)
#summary(new_dataset$RES1)

  
new_dataset <- new_dataset %>%
  filter(RES1 < 6)

new_dataset$RES2 <- as.numeric(new_dataset$RES2)
  

new_dataset <- new_dataset %>%
  filter(RES2 < 6)



new_dataset$RES2_R <- 6 - new_dataset$RES2

#describe(new_dataset$RES2)  
#summary(new_dataset$RES2)

new_dataset$RES3 <- as.numeric(new_dataset$RES3)
  
new_dataset <- new_dataset %>%
  filter(RES3 < 6)

#describe(new_dataset$RES3)  
#summary(new_dataset$RES3)

new_dataset$RES4 <- as.numeric(new_dataset$RES4)
  
new_dataset <- new_dataset %>%
  filter(RES4 < 6)

new_dataset$RES4_R <- 6 - new_dataset$RES4

#describe(new_dataset$RES4)  
#summary(new_dataset$RES4)

new_dataset$RES5 <- as.numeric(new_dataset$RES5)
  
new_dataset <- new_dataset %>%
  filter(RES5 < 6)

#describe(new_dataset$RES5)  
#summary(new_dataset$RES5)

new_dataset$RES6 <- as.numeric(new_dataset$RES6)
  
new_dataset <- new_dataset %>%
  filter(RES6 < 6)

new_dataset$RES6_R <- 6 - new_dataset$RES6

#describe(new_dataset$RES6)  
#summary(new_dataset$RES6)

new_dataset$SAT1 <- as.numeric(new_dataset$SAT1)
  
new_dataset <- new_dataset %>%
  filter(SAT1 < 6)

#describe(new_dataset$SAT1)  
#summary(new_dataset$SAT1)

new_dataset$SAT2 <- as.numeric(new_dataset$SAT2)
  
new_dataset <- new_dataset %>%
  filter(SAT2 < 6)

#describe(new_dataset$SAT2)  
#summary(new_dataset$SAT2)

new_dataset$SAT3 <- as.numeric(new_dataset$SAT3)
  
new_dataset <- new_dataset %>%
  filter(SAT3 < 6)

#describe(new_dataset$SAT3)  
#summary(new_dataset$SAT3)

new_dataset$SAT4 <- as.numeric(new_dataset$SAT4)
  
new_dataset <- new_dataset %>%
  filter(SAT4 < 6)

#describe(new_dataset$SAT4)  
#summary(new_dataset$SAT4)

new_dataset$SAT5 <- as.numeric(new_dataset$SAT5)
  
new_dataset <- new_dataset %>%
  filter(SAT5 < 6)

#describe(new_dataset$SAT5)  
#summary(new_dataset$SAT5)

new_dataset$LAD_NOW <- as.numeric(new_dataset$LAD_NOW)
  
new_dataset <- new_dataset %>%
  filter(LAD_NOW < 11)

#describe(new_dataset$LAD_NOW)  
#summary(new_dataset$LAD_NOW)

new_dataset$LAD_FUT <- as.numeric(new_dataset$LAD_FUT)
  
new_dataset <- new_dataset %>%
  filter(LAD_FUT < 11)

#describe(new_dataset$LAD_FUT)  
#summary(new_dataset$LAD_FUT)

#code to calculate social ladder variable
new_dataset$MOB_EXPECT<- new_dataset$LAD_FUT - new_dataset$LAD_NOW

```  

```{r}
#composite variables

#new_dataset <- new_dataset %>%
  #mutate(RES = rbind(rowMeans(cbind(RES1, RES2, RES3, RES4, RES5, RES6))))

#new_dataset <- new_dataset %>%
  #mutate(SAT = rbind(rowMeans(cbind(SAT1, SAT2, SAT3, SAT4, SAT5))))

new_dataset <- new_dataset %>%
  mutate(RES_composite = rowMeans(cbind(RES1, RES2_R, RES3, RES4_R, RES5, RES6_R)))

new_dataset <- new_dataset %>%
  mutate(SAT_composite = rowMeans(cbind(SAT1, SAT2, SAT3, SAT4, SAT5)))

```

```{r}

#summary descriptive statistics

new_dataset %>% 
  group_by(SEX) %>%
  dplyr::summarize(
     mean_RES   = mean(RES_composite),
     mean_SAT    = mean(SAT_composite),
     std_dev_RES = sd(RES_composite),
     std_dev_SAT = sd(SAT_composite),
     corr_RES_SAT  = cor(RES_composite, SAT_composite)
)

#Weak positive correlation between resilience and satisfaction when grouped by sex, where the correlation is slightly stronger in females. 
```
```{r}
#data distribution visualization


#ggplot(new_dataset, aes(x = SEX, y = RES)) + geom_violin(aes(fill=SEX)) + scale_fill_manual(values = c("Male" = "blue", "Female" = "pink")) + theme_classic()

#ggplot(new_dataset, aes(x = SEX, y = SAT)) + geom_violin(aes(fill=SEX)) + scale_fill_manual(values = c("Male" = "blue", "Female" = "pink")) + theme_classic()
```
```{r}

#violinBy(SAT ~ SEX, data = new_dataset, rain= TRUE, vertical = FALSE)

```
```{r}

#str(new_dataset)
#mo<-lm(data = new_dataset, MOB_EXPECT ~ RES_composite + SAT_composite)

#check_model(mo)


#ggplot(new_dataset, aes(x = RES_composite)) + geom_histogram(binwidth = 0.1) + theme_classic()

#ggplot(new_dataset, aes(x = SAT_composite)) + geom_histogram(binwidth = 0.1) + theme_classic()

```
```{r}

#Normality test for SAT, Shapiro

#shapiro.test(new_dataset$SAT)

#shapiro.test(new_dataset$RES)

```
```{r}
#new_dataset$SAT_log <- log10(new_dataset$SAT)

#ggplot(new_dataset, aes(x = SAT_log)) + geom_histogram(binwidth = 0.05) + theme_classic()

#new_dataset$RES_log <- log10(new_dataset$RES)

#ggplot(new_dataset, aes(x = RES_log)) + geom_histogram(binwidth = 0.05) + theme_classic()



```
```{r}

#shapiro.test(new_dataset$SAT_log)
#shapiro.test(new_dataset$RES_log)

#Based on the original histograms, RES seemed normal & SAT did not. Based on the S-W normality test, both were non-normal. Remained so depite log transformation

```
```{r}
#ggplot(new_dataset, aes(x = SEX, y = SAT)) +
 # geom_boxplot(aes(fill = SEX)) +
  #theme_minimal() +
  #labs(title = "Boxplot of SAT Scores by Sex", x = "Sex", y = "SAT Scores")
```

```{r}
#variance by group for variables RES & SAT

#var(new_dataset$RES)

#new_dataset %>%
 # group_by(SEX) %>%
  #summarize(Variance = var(RES))

#var(new_dataset$SAT)
```


```{r}
#new_dataset %>%
 # group_by(SEX) %>%
  #summarize(Variance = var(SAT))
```

```{r}
#ggplot(new_dataset, aes(x = SEX, y = MOB_EXPECT)) +
 # geom_boxplot(aes(fill = SEX)) +
  #theme_minimal() +
  #labs(title = "MOB_EXPECT by SEX", x = "Sex", y = "MOB_EXPECT")
```

```{r}
#correlation <- cor(new_dataset$MOB_EXPECT, new_dataset$SAT, use = "complete.obs")

#print(correlation)

```
```{r}

#simple correlation using ALL variables 

new_dataset <- new_dataset %>%
  select(SAT_composite, MOB_EXPECT, RES_composite, SEX)


Corr(new_dataset)

ggcorrmat(new_dataset)
```
```{r}
#Multiple regression

model<-lm(MOB_EXPECT ~ SAT_composite + RES_composite, data = new_dataset)

check_model(model)

model_summary(model)

tab_model(model)

plot_model(model,  type ="est",  show.values = TRUE, vline.color = "#1B191999", line.size = 1.5, dot.size = 2.5, colors = "blue") + theme_bruce()
```
```{r}

#moderation effect of GENDER on correlation between SAT_composite and MOB_expect


PROCESS(new_dataset, y = "MOB_EXPECT", x = "SAT_composite", mods = c("SEX"))

PROCESS(new_dataset, y = "MOB_EXPECT", x = "RES_composite", mods = c("SEX"))

```

```{r}

plot<-summarySE(new_dataset, measurevar="MOB_EXPECT", groupvars=c("SEX", "SAT_composite"))

as.factor

ggplot(plot, aes(x = SAT_composite, y = MOB_EXPECT)) +
 geom_smooth(method = lm) + geom_point() + facet_wrap(~ SEX) + theme_bruce()

plot<-summarySE(new_dataset, measurevar="MOB_EXPECT", groupvars=c("SEX", "RES_composite"))

ggplot(plot, aes(x = RES_composite, y = MOB_EXPECT)) +
 geom_smooth(method = lm) + geom_point() + facet_wrap(~ SEX) + theme_bruce()

```

```{r}
Alpha(da38964.0001, "SAT", c("1", "2", "3", "4", "5"))

Alpha(da38964.0001, "RES", 1:6, rev = c("RES2", "RES4", "RES6"))
```
```{r}
EFA(da38964.0001, "SAT", 1:5, method = "pa", plot.scree = TRUE, nfactors = c("parallel"))

EFA(da38964.0001, "RES", 1:6, rev = c("RES2", "RES4", "RES6"), method = "pa", plot.scree = TRUE, nfactors = c("parallel"))
```
```{r}

model<-lm(SAT_composite ~ MOB_EXPECT + RES_composite, data = new_dataset)

check_model(model)

model_summary(model)

tab_model(model)

plot_model(model,  type ="est",  show.values = TRUE, vline.color = "#1B191999", line.size = 1.5, dot.size = 2.5, colors = "blue") + theme_bruce()


```
```{r}

plot1 <- summarySE(new_dataset, measurevar = "SAT_composite", groupvars = c("SEX", "MOB_EXPECT"))

ggplot(plot1, aes(x = MOB_EXPECT, y = SAT_composite)) +
  geom_smooth(method = "lm") + 
  geom_point() + 
  facet_wrap(~ SEX) + 
  theme_get() +
  scale_x_continuous(name = "Social Mobility Expectations") +  # Rename x-axis
  scale_y_continuous(name = "Life Satisfaction") + # Rename y-axis
  theme(
    axis.title.x = element_text(color = "darkred", size = 16, family = "Arial", face = "italic"),
    axis.title.y = element_text(color = "darkred", size = 16, family = "Arial", face = "italic")
  )
  
 

plot2 <- summarySE(new_dataset, measurevar = "SAT_composite", groupvars = c("SEX", "RES_composite"))

ggplot(plot2, aes(x = RES_composite, y = SAT_composite)) +
  geom_smooth(method = "lm") + 
  geom_point() + 
  facet_wrap(~ SEX) + 
  theme_sjplot() +
  scale_x_continuous(name = "Resilience") + 
  scale_y_continuous(name = "Life Satisfaction") +  
  theme(
    axis.title.x = element_text(color = "darkred", size = 16, family = "Arial", face = "italic"),
    axis.title.y = element_text(color = "darkred", size = 16, family = "Arial", face = "italic")
  )
  

```
```{r}
sum(is.na(new_dataset$RES_composite))

colnames(new_dataset)

PROCESS(new_dataset, y = "SAT_composite", x = "MOB_EXPECT", mods = c("SEX"))

PROCESS(new_dataset, y = "SAT_composite", x = "RES_composite", mods = c("SEX"))

```

